Models/CampaignList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Webtracking.Models
{
    public class CampaignList
    {
        public string _id { get; set; }
        public string Name { get; set; }
        public int Openers { get; set; }
        public float OpenersRate { get; set; }
        public int Clickers { get; set; }
        public float ClickersRate { get; set; }
        public int Unsubscriptions { get; set; }
        public float UnsubscriptionsRate { get; set; }
        public int EmailSent { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace Webtracking.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ActionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Webtracking.Controllers
{
    public class ActionsController : Controller
    {
        private readonly ILogger<CampaignsController> _logger;

        public ActionsController(ILogger<CampaignsController> logger)
        {
            _logger = logger;
        }

        // GET: ActionsController
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult o(int id, string key)
        {
            try
            {
                return Redirect(Database.Campaign.GetTrackedLink(id, key));
            }
            catch(Exception ex)
            {
                _logger.LogError(ex.Message);
                throw ex;
            }
        }

        public ActionResult op(string id, string key)
        {
            try 
            { 
                Database.Campaign.LogOpener(key, id);
                Database.Campaign oCampaign = new Database.Campaign(new Guid(id));
                return Redirect(string.Format("https://{0}/ii.png", oCampaign.Domain));
            }
            catch(Exception ex)
            {
                _logger.LogError(ex.Message);
                throw ex;
            }
        }

        public ActionResult Unsubscribe(string id, string key)
        {
            try
            {
                Database.Campaign.LogUnsubscribe(key, id);
                return View();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                throw ex;
            }
            
        }
    }
}

Controllers/CampaignsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting.Server.Features;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Webtracking.Database;
using Webtracking.Models;

namespace Webtracking.Controllers
{
    public class CampaignsController : Controller
    {
        //TODO: manage the "Edit" a button of a campaign in the controler and the campaign management view
        //TODO: Create the view "details" to consult the statistics of a campaign (the view exist but not implemented).

        private readonly ILogger<CampaignsController> _logger;

        public CampaignsController(ILogger<CampaignsController> logger)
        {
            _logger = logger;
        }

        public IActionResult Edit(string id)
        {
            return View(new Database.Campaign(new Guid(id)));
        }

        public IActionResult Delete(string id)
        {
            Campaign oCamp = new Campaign(new Guid(id));
            oCamp.Remove();
            return RedirectToAction("Index"); 
        }

        [HttpPost]
        public IActionResult Edit(Database.Campaign oCampaign)
        {
            return View(oCampaign);
        }

        public IActionResult Details(string id)
        {
            //TODO: Add statistics and details
            return View(new Database.Campaign(new Guid(id)));
        }

        public IActionResult Index()
        {
            return View(Database.Campaign.GetListWStats());
        }

        [HttpGet]
        public IActionResult Tracker(string? id)
        {
            return View(new Database.Campaign(new Guid(id)));
        }

        [HttpPost]
        public IActionResult Tracker(string? id, Database.Campaign model)
        {
            if (!String.IsNullOrEmpty(model.OriginalBat))
            {
                model.TrackedBat = Campaign.TrackContent(model.OriginalBat, model.Domain, model.DynamicField, true, model.Name, model._id);
                model.Save();
            }
            return RedirectToAction("Tracker", new { id = model._id });
        }

        public IActionResult Create(Database.Campaign newCampaign)
        {
            if (string.IsNullOrEmpty(newCampaign.Name))
            {
                newCampaign.Domain = this.Request.HttpContext.Request.Host.ToString();
                return View(newCampaign);
            }
            else
            {
                if (newCampaign.Save())
                    return RedirectToAction("Index");
                else
                    return View(newCampaign);
            }
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Webtracking.Models;

namespace Webtracking.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/UnsubscribeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Webtracking.Controllers
{
    public class UnsubscribeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Actions/Unsubscribe.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Unsubscription</h1>
<div>
    your unsubscription has been registered. We hope to see you again soon on our platform
</div>

Views/Campaigns/Create.cshtml
@model Webtracking.Database.Campaign 

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Create</h1>
<h4>Campaign</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="custom-control-label"></label>
                <input asp-for="Name" title="Please use only alphanumeric characters (a-z A-Z 0-9) without space. "/>
                <span asp-validation-for="Name" class="custom-valisation"></span>
            </div>
            <div class="form-group">
                <label asp-for="Domain" class="custom-control-label"></label>
                <input asp-for="Domain" title="Please fill only the domain or subdomain of this application"/>
                <span asp-validation-for="Domain" class="custom-valisation"></span>
            </div>
            <div class="form-group">
                <label asp-for="DynamicField" class="custom-control-label"></label>
                <input asp-for="DynamicField" title="Please insert here, the tag used by your sending email software to define the receipient email"/>
                <span asp-validation-for="DynamicField" class="custom-valisation"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailSent" class="custom-control-label"></label>
                <input asp-for="EmailSent" title="Please fill here the total number of emails sent for this campaggne (to calculate the statistics)"/>
                <span asp-validation-for="EmailSent" class="custom-valisation"></span>
            </div>
            <div class="row">
                <input type="submit" value="Create" class="btn btn-primary" />&nbsp;&nbsp;<a class="btn btn-danger" asp-action="Index">Back to List</a>
            </div>
        </form>
    </div> 
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Campaigns/Details.cshtml
@model Webtracking.Database.Campaign

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Campaign</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmailSent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmailSent)
        </dd>
    </dl>
</div>
<div>//TODO: Add statistics and details</div>
<div>
     <a asp-action="Index" class="btn btn-danger">Back to List</a>
</div>

Views/Campaigns/Edit.cshtml
@model Webtracking.Database.Campaign

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<div>
    <h4>Campaign</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmailSent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmailSent)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Domain)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Domain)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DynamicField)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DynamicField)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {  id = Model._id }) &nbsp;&nbsp;<a asp-action="Index" class="btn btn-danger">Back to List</a>
</div>

Views/Campaigns/Index.cshtml
@model List<Webtracking.Models.CampaignList>

@{
    ViewData["Title"] = "ViewCampaign";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Campaign management</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Campaign</th>
            <th>Openers</th>
            <th>Clickers</th>
            <th>Unsubscriptions</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <span title="click on the name to show statistics">@Html.ActionLink(@item.Name, "Details", new { id = item._id }) ( @item.EmailSent )</span>
            </td>
            <td>@item.Openers ( @item.OpenersRate % )</td>
            <td>@item.Clickers  ( @item.ClickersRate % )</td>
            <td>@item.Unsubscriptions ( @item.UnsubscriptionsRate % )</td>
            <td>
                @Html.ActionLink("Tracker", "Tracker", new { id = item._id }) |
                @Html.ActionLink("Edit", "Edit", new { id = item._id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item._id }, new { onclick = "return confirm('Remove a campaign will remove definitivly the campaign AND all its statistics. Are you sure that you want remove it?');" })
            </td>
        </tr>}
    </tbody>
</table>

Views/Campaigns/Tracker.cshtml
@model Webtracking.Database.Campaign

@{
    ViewData["Title"] = "Tracker";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Bat Tracker</h1>

<div>
    <h4><label asp-for="Name"></label>&nbsp;&nbsp;@Html.DisplayFor(model => model.Name)</h4>
    <hr />
    <form asp-route-returnUrl="@ViewData["ReturnUrl"]" method="post">
        @Html.HiddenFor(m => m._id)
        @Html.HiddenFor(m => m.CreationDate)
        @Html.HiddenFor(m => m.EmailSent)
        @Html.HiddenFor(m => m.UpdatedDate)
        @Html.HiddenFor(m => m.Name)
        <div class="row">
            <div class="col-md-3">
                <label asp-for="Domain" class="custom-control-label"></label>
            </div>
            <div class="col-md-3">
                <input asp-for="Domain" />
                <span asp-validation-for="Domain" class="custom-valisation"></span>
            </div>
            <div class="col-md-3">
                <label asp-for="DynamicField" class="custom-control-label"></label>
            </div>
            <div class="col-md-3">
                <input asp-for="DynamicField" />
                <span asp-validation-for="DynamicField" class="custom-valisation"></span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <label asp-for="OriginalBat" class="custom-control-label"></label>
            </div>
            <div class="col-md-6">
                <label asp-for="TrackedBat" class="custom-control-label"></label>
            </div>
            <div class="col-md-6">
                <textarea asp-for="OriginalBat" cols="60" style="height: 400px;"></textarea>
                <span asp-validation-for="OriginalBat" class="custom-valisation"></span>
            </div>
            <div class="col-md-6">
                <textarea asp-for="TrackedBat" cols="60" style="height: 400px;"></textarea>
            </div>
            <div class="row">
                <button type="submit" onclick="return confirm('the BAT\'s tracking replaces its predecessor for the same campaign. Would you like to track this BAT? ');" class="btn btn-success">Track and save</button>&nbsp;&nbsp;<a class="btn btn-danger" asp-action="Index">Back to List</a>
            </div>
        </div>
    </form>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>free software under the GNU license. WebTracking is an emailing behavioral analysis tool to track.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Webtracking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Campaigns" asp-action="Index">Campaigns</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Webtracking - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Unsubscribe/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}